---
title: "Configure the model"
author: "Jen Schripsema"
date: '2022-07-27'
output: html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Configure the model

The PACE-HRH model simulates healthcare needs in a given populationto enable better health system
staffing decisions. PACE-HRH is a stochastic, agent-based model, meaning the individual people
accessing and working in the health system are simulated and there is randomness built into the
model behavior. To configure the model, you input data in Excel spreadsheets that describe
demographics, healthcare tasks, and available staff in the geographic region of interest. To begin,
navigate to the "config" directory and open the Excel workbook "R Model Inputs.xlsx".

<!--- Should we rename the file names to not include spaces? --->

The workbook is initially configured to model the Ethiopian Health Extension Program (HEP) and
contains values relevant to that context. You should edit the workbook parameters for the
particular context you are working in. 

The sections below describe each of the spreadsheets that are used as model inputs. You will see
each of these sheets in tabs across the bottom of the Excel workbook.

### Scenarios

The **Scenarios** sheet is the primary sheet that controls inputs to the model. It lists the
different healthcare scenarios you'd like to model. You may vary different parameters in each
scenario to compare different proposed healthcare staffing options. For example, the default values
hold the demographic and seasonality parameters consistent across scenarios but vary the healthcare
tasks and staffing cadres to model proposed health system policies.

#### Parameters

* **UniqueID**: The name of the scenario to model. The name must be unique and consistent across 
  all sheets. 
* **WeeksPerYr**: The number of working weeks in the year.
* **HrsPerWeek**: The number of hours each week a typical healthcare worker is expected to work.
* **BaselinePop**: The number of people in a typical healthcare catchment. Usually, these values are
  set as targets by a government healthcare program, such as the size of the population each
  primary healthcare facility is expected to serve. Value typically range from 10,000 to 20,000.
* **PopType**: The type of population modeled.
* **o_** columns F through J: (Optional) True/false binary values that turn on or off different 
  features of the model; to be used for debugging.
* **sheet_** columns K through N: The name of the sheets to use as inputs for **TaskValues**, 
  **PopValues**, **SeasonalityCurves**, and **Cadres** in the model. The function and format of each of those sheets is described in more detail below.
* **DeliveryModel**: The different healthcare delivery models for each of the scenarios.
* **Geography_dontedit**: Informational field that is populated by the **RegionSelect** sheet.

<!--- PopType wasn't covered in the video and I'm not entirely sure what this does in the model 
    It's also not clear to me what DeliveryModel does if someone wants to edit the model for
    other contexts --->

### RegionSelect

The **RegionSelect** sheet specifies the geographic region to be simulated.

#### Parameters

* **adminNameAsUsed**: The human-readable name for each administrative district. You may include 
  districts at different levels, for example an entire country and also the administrative 
  districts within that country. Provide the values in column F, which will populate the drop-down 
  menu in column B. The selection you make in column B will populate to other sheets in the 
  workbook. 
* **adminCode**: The unique numerical code for the administrative district. Provide the values in
  column G. Selecting from the drop-down menu in column B will populate the **adminCode** in column C. 

### TotalPop

The **TotalPop** sheet lists the number of people (male, female, and total) in each annual age bin, 
from 0 to 100.

### StochasticParameters

The **StochasticParameters** sheet lists the **p** and **q** values that determine the width of the 
stochastic distributions around various parameter values. 

<!--- Brittany to provide more detail for each of these values. --->

### PopValues

The **PopValues** sheet contains fertility and mortality rates for different groups in the
population. Fertility rates are specified as births per woman per year and will add people to the
simulated population. Mortality rates are specified per individual per year and will remove people.
All rates (and rates of change) in the model are stochastic; the value you specify is the mean in a distribution.  The first row, "Annual birth rate male," is the fertility rate applied to males (so it should be zero); this is necessary for running the model. Blank values are treated as zeroes. 

Columns A through F define standard categories and shouldn't need to be modified unless you plan to
add functionality to the model itself. Default values are sourced from Ethiopian DHS data but
should be changed for your context. If you look at the equation in each cell, you can see that the
data is being sourced from another sheet in the workbook. However, the **PopValues** sheet is the
one used as an input to the model, so values can be changed directly here if you prefer. 

#### Parameters

* **Description**: The human-readable demographics category.
* **Label**: The unique string that defines that category.
* **Type**: The type of rate describes, mortality or fertility.
* **Sex**: The sex to which the rate applies.
* **BandStart**: The youngest age to which the rate applies.
* **BandEnd**: The oldest age to which the rate applies.
* **InitValue**: The rate value at the beginning of the simulation.
* **ChangeRate**: The annual change in rate over the course of the simulation. A value of 1 
  indicates no change, a value above 1 indicates the rate is increasing over time, and a value
  below 1 indicates the rate is decreasing. For example, the age 15-19 initial fertility rate of 0.072 will be 0.0712 (0.72 * 0.988469278) after one year.
* **ValueCode**: The unique string identifying the category. These are useful when analyzing model 
  outputs. 


### TaskValues

The **TaskValues** sheets describe the specific healthcare tasks that are completed by the
healthcare workers. The model provides a reference sheet (**TaskValues_ref**) that lists a
comprehensive range of healthcare tasks, such as vaccination, education about contraceptives,
antinatal care, etc. 

You can then provide one or more **TaskValues** sheets that describe who receives and performs the
healthcare tasks, how often, and for how long. These sheets are specified as inputs to the model
via the **Scenarios** sheet. For example, by default there are three **TaskValues**
sheets: **TV_Basic**, **TV_Comprehensive**, and **TV_Merged**. These are quite similar, but have
different subsets of data to mimic the delivery models of the three different scenarios. You can
set these sheets up to include whichever sets of healthcare services you are delivering in the
scenarios you want to model. You could also have different healthcare services available for
different regions.

Columns A through D are only for reference from the original data source and are not used as inputs
to the model. Columns G through I are not used as inputs but can be valuable for post-hoc analysis
and summary statistics. Columns L through P jointly determine how many resources are required for a given task by specifying how many contacts with the healthcare system are required for a given task, how long each contact takes, and the number of people that received care. 

#### Parameters

* **Indicator**: A unique ID. For example, the indicator FH.MN.ANC.1 indicates Family Health, Maternal and Newborn, Antenatal, and first task. 
* **CommonName**: The human-readable common name for the task.
* **ClinicalOrNon**: Indicates if the task is clinical or non-clinical.
* **ClinicalCat**: The clinical category for the task.
* **ServiceCat**: The service category for the task.
* **RelevantPop**: The population to which this healthcare task applies, selected via a drop-down 
  menu. For example, antenatal care is proportional to the number of births. Cervical cancer care is proportional to the population of women of child-bearing age. The value changes which population the tasks are applied to in the model.
  
* **Geography** is automatically filled based on the region specified in the RegionSelect sheet. 
* **StartingRateInPop**
* **RateMultiplier**
* **AnnualDeltaRatio**
* **NumContactsPerUnit**:
* **NumContactsAnnual**:
* **MinsPerContact**:
* **HoursPerWeek**:
* **FTERatio**:


* 

* StartingRateInPop the proportion of hte relevant population that recieves this care. So for example, this value is 1 for antenatal care visits because every pregnant person requires those visits. (how does this account for miscarriage?)

* RateMultiplier Multiplier that accounts for tasks that happen in excess of the number of people in the eligible population. For example, you would use HIV incidence rate as the StartRateInPop for HIV testing but some proporition of people that recieve tests will test negative. This proportion of true negatives will be the RateMultiplier such that StartRateinPop multiplied by RateMultipler will equal the number of people who will receive that care.

* **AnnualDeltaRate** change year over year

* NumContactsPerUnit The number of contacts with the healthcare system per person who is eligible for this task. In this example four antenatal care visits per birth are recommended. 

* NumContactsAnnual functionally does the same thing but is indicated for routine preventive care that happens per an annual scheduled and is'nt based on a child's age or condition, for example

* MinsPerContact The number of minutes required by teh clinician (of any type) to complete this task with an individual. 

* HoursPerWeek: The estimated number of hours per week for non-clinical tasks that are not directly related to a population level. For example, there may be a few hours of administrative tasks required regardless of clinical care provided. 

### SeasonalityCurves

This sheet describes birth seasonality and the seasonality of conditions like malnutrition, TB, malaria, and diarrhea. Each month of the year is listed in a row and each cell in a given column represents the proportion of those births or conditions that occur in a given month. The values in each column should sum to 1. If they don't sum to 1, the model will normalize the values; however, this may be a source of bugs. So if you see unexpected behavior in the seasonality, we recommend verifying the values indicated there. You can add additional curves ifyou like, these are hte ones relevnat to this deefautl population. For example, you can see that malnutrition is highest between September and January and lower the rest of the year.

### SeasonalityOffsets

This sheet contains a list of the tasks that are affected by seasonality and their timing offsets from that seasonal curve, if any. Offsets are specified in months: negative values indicate the number of months prior to the event described by the seaosnal curve, positive values are after, and values of zero indicate there is no time offset from the curve.  The name of the curve listed in this sheet must match the name of hte curve in SeasonalityCurves sheet 

For example, antenatal care visits are related to birth seasonality but precede those births by some period of time. The first round of treatment for malnutrition will not have an offset from the malnutriion seaosnal curve, but followup visits occur at the 1, 2, and 3 month offsets. The number of contacts listed in the offset table should match the number of contacts listed in teh TaskValue sheests for that particular tasks. In other words, if four antenatal care visits are recommended, four offsets should be listed in this sheet.

Up to six offset contacts can be specified in the model; additional contacts would require

### Cadres

Cadre sheets define the type of clinician (community health worker, nurse, doctor, etc) responsible for each type of healthcare task. You may have one or more of these sheets for the scenarios you are modeling. THe cadre used for each scenario is defined in the **Scenarios** sheet in the column **sheet_Cadre**. 

For example, the examples in the default Ethiopia model has some tasks being shifted from certain cadres of workers to other workers over time as staffing shifts, and each scenario models this shift in responsibilities slightly differently. The nubmers and names o fht ecolumns can be changed, but it must be consistent across sheets. The total column isnt' fed into the model but is a check to be sure the staff assignments sum to 100% correctly. 

In the Cadres_Comprehensive sheet, you see the ANC visists start out as being soley the responsibiltiy of the Health Extension WOrkers (HEW) and then shift entirely to a cadre of new midwife staff members in 2025. A more complex example is the Pneumonia (ARI) tasks, which starts ad the responsibility of the Health Extension WOrkers and then gradually shifts the Health Officers, FamilyHealth Officer, and Nurses. 

It's very important that every task value indicator appears in the Cadres sheets. 

## REgionalData

This is the source file for all of the region data V lookups. This is the source of truth for all of those values in other sheets. This includes starting rate in population (pulled in for ). If you want to retain the mlutigeography structure of how the model is currently set up, you can change the values here. Otherwise, youc an change the values in teh TaskValues sheetts
