---
title: "Configure the model"
author: "Jen Schripsema"
date: '2022-07-27'
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{The results structure}
%\VignetteEngine{knitr::rmarkdown}
%\VignetteEncoding{UTF-8}
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting started with the PACE-HRH model 

## Configure the model

The PACE-HRH model simulates healthcare needs in a given population to enable better health system
staffing decisions. PACE-HRH is a stochastic, Monte Carlo simulation model, meaning that the population, its healthcare needs, and the time required to meet those are simulated and there is randomness built into the model uncertainty in the population's size, growth, and healthcare needs. 
To configure the model, you input data in Excel spreadsheets that describe the population's
demographics, healthcare tasks, and available staff in the geographic region of interest. To begin,
navigate to the "config" directory and open the Excel workbook "R Model Inputs.xlsx".

<!--- Should we rename the file names to not include spaces? --->

The workbook is initially configured to model a simple set of tasks and contains example values. You should edit the workbook parameters for the particular context you are working in. 

The sections below describe each of the spreadsheets that are used as model inputs. You will see
each of these sheets in tabs across the bottom of the Excel workbook.

### Scenarios

The **Scenarios** sheet is the primary sheet that controls inputs to the model. Every row is a separate scenario and  lists the different healthcare scenarios that you'd like to model. You may vary parameters in each scenario to compare different proposed healthcare staffing options by changing the relevant values or the tab specified to be used. For example, the default values hold the demographic and seasonality parameters consistent across scenarios but vary the healthcare tasks and staffing cadres to model proposed health system policies.

#### Parameters

* **UniqueID**: The name of the scenario to model. The name must be unique and will be used to name the results output files after the simulation runs. This can be any useful description, but should not include special characters. 
* **WeeksPerYr**: The number of working weeks in the year, excluding time off and absenteeism. For example, if a typical worker has 2 weeks of vacation and is absent 3 weeks per year, then this value would be 52-2-3=47.
* **HrsPerWeek**: The number of hours each week a typical healthcare worker is expected to work, excluding breaks and on-call time. This should typically be less than 40.
* **BaselinePop**: The number of people in a typical healthcare catchment. Usually, these values are
  set as targets by a government healthcare program, such as the size of the population each
  primary healthcare facility is expected to serve. Value typically range from 5,000 to 20,000.
* **o_PopGrowth** Typically this should be set to TRUE. Optionally, this true/false binary value turns on or off the growth of the population. If set to TRUE, the population size will grow at a rate dependent on the fertility and mortality (set elsewhere). If set to FALSE, the population pyramid will evolve per the fertility and mortality, but the total population will be normalized to the **BaselinePop** value every year, stabilizing population size. This is to be used for debugging and sensitivity analysis.
* **o_Seasonality** Typically this should be set to TRUE. Optionally, this true/false binary value turns on or off the seasonality. If set to TRUE, seasonality curves will be applied to the relevant tasks (set elsewhere). If set to FALSE, seasonality will be turned off. This is to be used for debugging and sensitivity analysis.
* **o_Fertility_decr** Typically this should be set to TRUE. Optionally, this true/false binary value turns on or off the decline in the fertility rate. If set to TRUE, fertility rates will decline over time (set elsewhere). If set to FALSE, fertility will remain stable at the level set for the first year of the simulation. This is to be used for debugging and sensitivity analysis.
* **o_MHIVTB_decr** Typically this should be set to TRUE. Optionally, this true/false binary value turns on or off the decline in the incidence rates for malaria, HIV, and TB. If set to TRUE, incidence rates will decline over time (set elsewhere). If set to FALSE, these rates will remain stable at the level set for the first year of the simulation. This is to be used for debugging and sensitivity analysis.
* **o_ChildDis_decr** Typically this should be set to TRUE. Optionally, this true/false binary value turns on or off the decline in the incidence rates for childhood diseases. If set to TRUE, incidence rates will decline over time (set elsewhere). If set to FALSE, these rates will remain stable at the level set for the first year of the simulation. This is to be used for debugging and sensitivity analysis.
* **sheet_** columns K through N: The name of the sheets to use as inputs for **TaskValues**, 
  **PopValues**, **SeasonalityCurves**, and **Cadres** in the model. The function and format of each of those sheets is described in more detail below.
* **DeliveryModel**: A text description for the healthcare delivery model scenario. This is for user reference only and does not change how the model functions.
* **Geography_dontedit**: Informational field that is populated by the **RegionSelect** sheet. Do not edit here, as it will not affect the functioning of the model but is automatically used for naming the results files and may result in confusion if it is changed manually.

### RegionSelect

The **RegionSelect** sheet specifies the geographic region to be simulated. 

#### Parameters

* **adminNameAsUsed**: The human-readable name for each administrative unit. You may include 
  units at different levels, for example an entire country and also the administrative 
  districts within that country. Provide the values in column F, which will populate the drop-down 
  menu in column B. The selection you make in column B will populate to the relevant population, fertility, mortality, and incidence rates are updated throughout the workbook.
* **adminCode**: The unique numerical code for the administrative district. Provide the values in
  column G. Selecting from the drop-down menu in column B will populate the **adminCode** in column C. 

### TotalPop

The **TotalPop** sheet lists the number of people (male, female, and total) in each annual age bin, 
from 0 to 100. Optionally, multiple **TotalPop** tabs can be created and referenced in the **Scenarios** tab.

### StochasticParameters

The **StochasticParameters** sheet lists the **p** and **q** values that determine the width of the 
stochastic distributions around various parameter values. See the table below for more detail.

| Value                                              | Distribution             | Value inputs     | Parameters                                       |
|:-------------------------------------------------- |:-------------------------|:-----------------|:-------------------------------------------------|
| Fertility rates                                               | Uniform                  | mean, p          | min = mean - mean\*p <br /> max = mean + mean\*p |
| Mortality rates                                               | Uniform                  | mean, p          | min = mean - mean\*p <br /> max = mean + mean\*p |
| Incidence rates <br />(**TaskValues** column H)               | Uniform                  | mean, p          | min = mean - mean\*p <br /> max = mean + mean\*p |
| Annual delta fertility rates                                  | Truncated normal*        | delta, p, q      | mean = delta <br /> std dev = p <br /> a = mean - p\*q <br /> b = mean + p\*q  |
| Annual delta mortality rates                                  | Truncated normal*        | delta, p, q      |  mean = delta <br /> std dev = p <br /> a = mean - p\*q <br /> b = mean + p\*q | 
| Annual delta incidence rates <br />(**TaskValues** column L)  | Truncated normal*        | delta, p, q      |  mean = delta <br /> std dev = p <br /> a = mean - p\*q <br /> b = mean + p\*q |
| Seasonality ratio to mean                                     | Uniform                  | mean, p          | min = mean - mean\*p <br /> max = mean + mean\*p |
| Minutes per contact <br />(optional; **TaskValues** column O) | Lognormal                | mean, p          | s = mean\*p <br /> meanlog = log(m)-12log[(s/m)2+1] <br /> sdlog = sqrt(log(s/m)^2 + 1 |
| Hours per week <br />(optional; **TaskValues** column P)      | Uniform                  | mean, p          | min = mean - mean\*p <br /> max = mean + mean\*p |     

\* Truncated normal can be done in R using the truncnorm package.  

We are approximating a Markov random walk with drift. The error term is generally modeled with a normal 
distribution, plus an additional drift distribution. Here we use just one parameter. There is some 
evidence that a Weibull distribution is also a good option. 

### PopValues

The **PopValues** sheet contains fertility and mortality rates for different groups in the
population. Fertility rates are specified as births per woman per year and will add people to the
simulated population. Mortality rates are specified per individual per year and will remove people.
All rates (and rates of change) in the model are stochastic; the value you specify is the mean in a distribution and the variance is determined by the 'p' and 'q' parameters set on the **StochasticParameters** tab.  The first row, "Annual birth rate male," is the fertility rate applied to males (so it should always be set to zero); this is necessary for running the model. Blank values are treated as zeroes. 

<!--- Charles: What happens if someone doesn't input a row that covers the pop all the way to 100? E.g. if someone didn't put in fertility for women over 50, does that throw an error, or default to 0, or...? --->

Columns A through F define standard categories and shouldn't need to be modified unless you plan to
add functionality to the model itself. Default values are sourced from Ethiopian DHS data but
should be changed for your context. If you look at the equation in each cell, you can see that the
data is being sourced from another sheet in the workbook. However, the **PopValues** sheet is the
one used as an input to the model, so values can be changed directly here if you prefer. 

#### Parameters

* **Description**: The human-readable demographics category. This does not affect the model's functionality and is for readibility only.
* **Label**: The unique string that defines that category.
* **Type**: The type of rate describes, mortality or fertility.
* **Sex**: The sex to which the rate applies.
* **BandStart**: The youngest age to which the rate applies.
* **BandEnd**: The oldest age to which the rate applies. Note: Be sure that the population age bands do not overlap, or multiple rates will be applied to the same people.
* **InitValue**: The rate value at the beginning of the simulation.
* **ChangeRate**: The annual change in rate over the course of the simulation. A value of 1 
  indicates no change, a value above 1 indicates the rate is increasing over time, and a value
  below 1 indicates the rate is decreasing. For example, the age 15-19 initial fertility rate of 0.072 will be 0.0712 (0.72 * 0.988469278) after one year.
* **ValueCode**: The unique string identifying the category. These are useful when analyzing model 
  outputs. 

<!--- Charles: Why are there blank values in the template? Can we fill in the labels and columns E/F or does that mess something up? --->

### TaskValues

The **TaskValues** sheets describe the specific healthcare tasks that are completed by the
healthcare workers. The model provides a reference sheet (**TaskValues_ref**) that lists a
comprehensive range of healthcare tasks, such as vaccination, education about contraceptives,
antenatal care, etc. You can down-select the tasks included in your model by deleting rows on the reference sheet and all other **TaskValues** sheets.

You can then provide one or more **TaskValues** sheets that describe who receives and performs the
healthcare tasks, how often, and for how long. These sheets are specified as inputs to the model
via the **Scenarios** sheet. For example, by default there are three **TaskValues**
sheets: **TV_Basic** and **TV_Comprehensive**. These are quite similar, but have
different subsets of tasks listed, to differentiate different delivery model scenarios. You can
set these sheets up to include whichever sets of healthcare services you are delivering in the
scenarios you want to model. You could also have different healthcare services available for
different regions, which would require the creation of additional **TV_** tabs.

Columns A through D are only for reference from the original data source and are not used as inputs
to the model. Columns G through I do not affect the running of the model, but are used in the automatic creation of summary statistics and can be used for manually post-processing the results. Columns L through P jointly determine how many resources are required for a given task by specifying how many contacts with the healthcare system are required for a given task, how long each contact takes, and the number of proportion of people that received care. 

#### Parameters

* **Indicator**: A unique ID. For example, the indicator FH.MN.ANC.1 indicates Family Health, Maternal and Newborn, Antenatal, and first task. These can be set to any useful text (excluding special characters), but each row must be a unique value.
* **CommonName**: The human-readable common name for the task.
* **ClinicalOrNon**: Indicates if the task is clinical, non-clinical, or non-productive.
* **ClinicalCat**: The sub-category for the task. These can be any text value that is useful.
* **ServiceCat**: The sub-sub-category for the task. These can be any text value that is useful.
* **RelevantPop**: The population to which this healthcare task applies, selected via a drop-down 
  menu. For example, antenatal care is proportional to the number of births. Cervical cancer care is proportional to the population of women of child-bearing age. This value changes which population the task is applied to in the model. Additional populations cannot be specified via the **R Model Inputs** file.
* **Geography**: Automatically filled based on the region specified in the **RegionSelect** sheet. Do not change this column manually.
* **StartingRateInPop**: The proportion of the relevant population that receives this care. For
  example, the value for antenatal care visits is 1 because every new birth requires that care. This value should not exceed 1.0.
* **RateMultiplier**: A multiplier to account for tasks that happen in excess of the number of 
  people in the eligible population. For example, you would use HIV incidence rate as the 
  **StartingRateInPop** for HIV testing, but some proportion of the people that receive tests do 
  not have HIV. The proportion of true negatives will be the **RateMultiplier** such that the 
  **StartingRateInPop** * **RateMultiplier** is equal to the number of people who receive testing.
* **AnnualDeltaRatio**: The annual change in the proportion of the relevant population who receives
  care. For diseases declining in prevalence, this should be below less than 1.0 (e.g. childhood parasites). For diseases increasing in prevalence, this should typically be greater than 1.0.
* **NumContactsPerUnit**: The number of contacts with the healthcare system per person who is 
  eligible to receive this task. In the default example, four antenatal care visits per birth are
  recommended.
* **NumContactsAnnual**: The number of contacts with the healthcare system per person annually for
  this task. Used for routine preventative care that happens on an annual schedule and isn't based
  on age or condition. Most tasks will have either a number of contacts per unit or a number of contacts annual, but not both.
* **MinsPerContact**: The number of minutes required by the healthcare worker to complete this task
  with an individual. This value should typically range between 5 and 30 minutes. 
* **HoursPerWeek**: The number of hours per week a healthcare workers spends on a task, usually a non-clinical task that is not directly related to population rates. For example, there may be a few hours of weekly administrative tasks required, regardless of clinical care provided. Community engagement, outreach, and supply management may also be tasks with this dynamic.

### SeasonalityCurves

The **SeasonlityCurves** sheet describes birth seasonality and the seasonality of conditions like
malnutrition, TB, malaria, and diarrhea. Each month of the year is listed in a row and each cell in
a given column represents the proportion of those births or conditions that occur in a given month.
For example, in the demonstration curves, you can see that malnutrition is highest between September and January and lower the rest of the year.

The values in each column should sum to 1. If they don't sum to 1, the model will normalize the
values; however, this may be a source of unexpected behavior. If you see strange seasonal patterns,
we recommend verifying the sum of these values. 

You can add seasonality curves for additional conditions if desired by adding additional named columns. If you do so, you can then reference them on the **SeasonalityOffsets** tab. 

The **SeasonalityCurves** tab is referenced in the **Scenarios** manager. If you want to run scenarios with different seasonality curves, you can duplicate the **SeasonalityCurves** tab, modify it, and reference the different tabs in the **Scenarios** column M.


### SeasonalityOffsets

The **SeasonalityOffsets** sheet contains a list of the tasks that are affected by seasonality and
how they are offset from (occurring before or after) the seasonality curves. Offsets are
specified in months: negative values indicate the number of months prior to the event described by
the seasonal curve, positive values are after, and values of zero indicate there is no time offset
from the curve. The name of the curve listed in this sheet must match the name of the curve in
the **SeasonalityCurves** sheet.

For example, antenatal care visits are related to birth seasonality but precede those births by some
period of time. The first round of treatment for malnutrition will not have an offset from the
malnutrition seasonality curve, but followup visits occur at the 1, 2, and 3 month offsets. The
number of contacts with the healthcare system listed in the offset table should match the number of
contacts listed in the **TaskValue** sheets for that particular task. In other words, if four
antenatal care visits are recommended, four offsets should be listed in this sheet.

Up to six offset contacts can be specified in the model; additional contacts would require updates
to the model code.

### Cadres

The **Cadres** sheets define the type of clinician (community health worker, nurse, doctor, etc.)
responsible for each type of healthcare task. You may have one or more of these sheets for the
scenarios you are modeling. The cadre used for each scenario is defined in the **Scenarios** sheet
in the column **sheet_Cadre**. It's very important that every task value unique identifier appears in
the **Cadres** sheets because otherwise the tasks will be unassigned and thus uncounted. If you have unexpectedly low workload assigned to certain cadres of workers, this is a possible source of the error.

For example, the default Ethiopian example has some tasks being shifted from certain
cadres of workers to other workers over time as staffing shifts, and each scenario models this
shift in responsibilities slightly differently. The numbers and names of the columns can be
changed, but the must be consistent across all sheets and must use the format of YY_CadreName where YY is the last two digits in a year, such as YY=30 for 2030. The year represents the first year in which this allocation is made; the allocation remains in place for the remaining years unless an additional assignment is made. 

The total column isn't fed into the model, but is a visual check to be sure the staff assignments sum to 100% correctly. If the total column is above or below 100%, this will result in either under-assignment or duplicative assignment of task time. If you have unexpected workload assigned to certain cadres of workers, this is a possible source of the error.

For example, in the **Cadres_Comprehensive** sheet, you see the ANC visits start out as being solely
the responsibility of the Health Extension Workers (HEWs) and then shift entirely to a cadre of new
midwife staff members in 2025. A more complex example is the Pneumonia (ARI) tasks, which start as
the responsibility of the HEWs and then gradually shift to the Health Officers, Family Health
Officer, and Nurses. 

### RegionalData

The **RegionalData** sheet is the source file for all of the regional data included in other sheets
that is pulled in via VLOOKUP in Excel. For example, the **StartingRateInPop** used in
the **TaskValues** sheet comes from the source values in this sheet. If you want to retain the
multi-geography structure currently used in the model, we recommend changing the values here.
However, the model pulls from the sheets listed above, so you can also change the values directly
in those sheets.

## Run the model

The PACE-HRH model simulates healthcare needs in a given population to enable
better health system staffing decisions. The model is configured via Excel
sheets and run via an R script. 

<!--- Rui: Can you update this based on the new process, given Charles' new functions and our incorporation of the geography name in the file output names? --->

Open the run simulations.R script

1.  Close "R Model Inputs.xslx" in Excel. RStudio will be unable to load the input values
    if the file is open. 
2.  Open the "Run simulations.R" script in RStudio. 
3.  From the **Tools** menu, select **Install Packages ...**.
4.  Under **Install from:**, select the most recent version of the PACE-HRH package binary zip file.
5.  Select the installation location and then click **Install**. 
6.  You may see a banner at the top of the screen that indicates some dependent packages that are 
    required. Select **Yes**. to enable installation.
7.  In the R code, set *numtrials* to the number of simulations you want to run. 100 tends to be good; 
    higher values can take longer because of the stochasticity in the model.
8.  Set the *date*. This can be in any format; follow a version control naming convention that makes 
    sense to you.
9.  Run the script. 

    The scenarios are loaded in line 16 and line 18 onward runs the model for each
    scenario. The results are saved out to a CSV file. The console will beep at you when the model
    has finished running. 
