---
title: "Configure the model"
author: "Jen Schripsema"
date: '2022-07-27'
output: html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Run the model

The PACE-HRH model simulates healthcare needs in a given population to enable
better health system staffing decisions. The model is configured via Excel
sheets (see Configure the model) and run via an R script. 

Open the run simulations.R script

1.  Close "R Model Inputs.xslx" in Excel. RStudio will be unable to load the input values
    if the file is open. 
2.  Open the "Run simulations.R" script in RStudio. 
3.  From the **Tools** menu, select **Install Packages ...**.
4.  Under **Install from:**, select the most recent version of the PACE-HRH package binary zip file.
5.  Select the installation location and then click **Install**. 
6.  You may see a banner at the top of the screen that indicates some dependent packages that are 
    required. Select **Yes**. to enable installation.
7.  In the R code, set *numtrials* to the number of simulations you want to run. 100 tends to be good; 
    higher values can take longer because of the stochasticity in the model.
8.  Set the *date*. This can be in any format; follow a version control naming convention that makes 
    sense to you.
9.  Run the script. 

    The scenarios are loaded in line 16 and line 18 onward runs the model for each
    scenario. The results are saved out to a CSV file. The console will beep at you when the model
    has finished running. 