---
title: "Test Seasonality"
author: "Meikang Wu"
date: "9/12/2022"
output:
  html_document:
    df_print: kable
  word_document: default
---

```{r setup, include=FALSE, warning=FALSE}
library(pacehrh)
```

## Run and Load Results
```{r echo=FALSE, warning=FALSE}
source("Run_simulations.R")

simple_seasonal_tasks <- pacehrh:::loadSeasonalityOffsets() %>%  
  # filter(Offset1 ==0) %>% 
  # filter_at(vars(-Offset1 & starts_with('Offset')), all_vars(is.na(.)))%>%
  select(Task) %>% 
  .$Task

DR_test <- DR_test %>% 
  filter(Task_ID %in% simple_seasonal_tasks) %>%
  select(Task_ID, Scenario_ID, Year, Month, Service_time, Num_services, Trial_num, Run_num)

head(DR_test)
```
## Get rid of first and last year for offset issue
```{r}
DR_test <- DR_test %>% 
  filter(Year > 2021) %>%
  filter(Year < 2039)
```
## Calculate average service

```{r}
avg_service <- DR_test %>% 
  group_by(Task_ID, Scenario_ID, Year, Month) %>%
  summarize(mean_total_service = mean(Service_time)) 

```


## Loop over tasks
```{r}
# Uncomplicated malaria in adults
scenarios <- c("BasicModel", "ComprehensiveModel", "MergedModel")
# scenario <- "BasicModel"
# task <- "DPC.Mlr.103A"
# type <- "Malaria"

simple_so <- pacehrh:::loadSeasonalityOffsets() # %>% filter(Offset1 ==0) %>% filter(if_all(-c(Task, Description, Curve, Offset1 ), ~ is.na(.)))
for (scanerio in scenarios){
  for(i in 1:nrow(simple_so)) {       # for-loop over rows
    task <- as.character(simple_so[i, "Task"])
    type <- as.character(simple_so[i, "Curve"])
    # filter to the target task
    target_service <- avg_service %>% 
    filter(Scenario_ID == scenario) %>%
    filter(Task_ID == task) %>%
    arrange(Year, Month) %>% 
    select(mean_total_service) %>%
    .$mean_total_service
  
    if (length(target_service) >0){
      # Create time series
      service_timeseries <- ts(target_service, frequency=12, start=c(min(DR_test$Year),1))
      
      # Plot time series
      # plot.ts(service_timeseries)
      
      # plot log time series
      #logservice_timeseries  <- log(service_timeseries)
      #plot.ts(logservice_timeseries)
      
      # decompose 
      # components <- decompose(service_timeseries, type='multiplicative')
      components <- decompose(service_timeseries, type='additive')
      decomposed_seasonal <- colMeans(matrix(components$seasonal, ncol = 12, byrow = TRUE))
      # plot(components)
      
      # TODO: Calculate expected seasonality with offset  
      # expected_seasonal <- as.vector(pacehrh:::loadSeasonalityCurves()[type])
      
      base_expected_seasonal <- as.vector(pacehrh:::loadSeasonalityCurves()[type][[1]])
      lags <- vector()
      total <- 0
      for (i2 in seq(1:6)){
        offset <- glue::glue("Offset{as.character(i2)}")
        if(!is.na(as.integer(simple_so[i, offset]))){
          total <- total + 1
          if (length(lags) ==0){
            lags <- DescTools::VecRot(base_expected_seasonal, as.integer(simple_so[i, offset]))
          }
          else{
            lags <- lags + DescTools::VecRot(base_expected_seasonal, as.integer(simple_so[i, offset]))
          }
        }
      }
      expected_seasonal <- lags / total
      
      if (all(abs(base_expected_seasonal - expected_seasonal) < 1e-6)){
        use_offset <- "non_offset"
      }
      else {
        use_offset <- "offeset"
      }
      
      # expected_data <- scale(expected_seasonal)
      # actual_data <- scale(decomposed_seasonal)
      # month <- seq_along(1:length(expected_seasonal))
      # seasonal_result <- data.frame(month, expected_data, actual_data)
      # ggplot2::ggplot() + 
      # geom_line(data = seasonal_result, aes(x = month, y = actual_data), color = "blue") +
      # geom_line(data = seasonal_result, aes(x = month, y = expected_data), color = "red") +
      # ggtitle(glue::glue("{scenario}_{task}_{type}_{use_offset}"))            
      par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
      plot(x = seq_along(1:length(expected_seasonal)),
           y=scale(expected_seasonal),
           #ylim = c(0, 20),
           type = "b", col='red',
           xlab = "Month",
           ylab = "Weight %")
      lines(x = seq_along(1:length(expected_seasonal))
            , y=scale(decomposed_seasonal),
             type = 'b', col='blue',  lty = 2)
      legend("top",
             inset = c(-0.4,0),
             legend = c("expected", "actual"),
             lty = 1,
             col = c("red","blue"))
      title(main = glue::glue("{scenario}_{task}_{type}_{use_offset}"))
    }
  }
}


```
