---
options:
  lin.eq.eps: 1e-08
  lin.ineq.eps: 1e-08
---

rules:
- expr: ''in_range(Year0, min=0.0, max=1.0)''
  name: CoverageRage_range
  label: CoverageRage_range
  description: |
    Coverage rate must be between 0.0 and 1.0
  meta:
    severity: error