---
options:
  lin.eq.eps: 1e-08
  lin.ineq.eps: 1e-08
---

rules:
- expr: 'if(!is.na(StartingRateInPop)) !is.na(AnnualDeltaRatio)'
  name: Missing_AnnualDeltaRatio_value
  label: Missing_AnnualDeltaRatio_value
  description: |
    AnnualDeltaRatio cannot be empty if the starting rate in pop contains a value.
    If the starting rate does not change, then the delta ratio should be 1.0.
    For example, all children should be vaccinated, so the starting rate and delta ratio should both be set to 1.0,
    indicating that 100% of eligible children should continue to be vaccinated every year.
  meta:
    severity: error
- expr: 'if(!is.na(StartingRateInPop)) !is.na(Indicator)'
  name: Indicator
  label: Indicator
  description: |
    The indicator name should not be empty if there is an initial rate.
    The lack of an indicator name will result in this row being ignored in the model and thus not included in the results.
  meta:
    severity: error
- expr: 'is.na(RateMultiplier)'
  name: RateMultiplier
  label: RateMultiplier
  description: |
    RateMultiplier is present
  meta:
    severity: info
- expr: 'if(!is.na(StartingRateInPop)) !is.na(NumContactsPerUnit) | ! is.na(NumContactsAnnual)'
  name: NumContacts_Frequency
  label: NumContacts_Frequency
  description: |
    If StartingRateInPop contains value, NumContactsPerUnit and NumContactsAnnual should not both be empty.
  meta:
    severity: error
- expr: '!(!is.na(NumContactsPerUnit) & !is.na(NumContactsAnnual))'
  name: NumContacts_Frequency_Duplicate
  label: NumContacts_Frequency_Duplicate
  description: |
    NumContactsPerUnit and NumContactsAnnual should not both contain value.
  meta:
    severity: warning
- expr: 'if(!is.na(StartingRateInPop)) !is.na(MinsPerContact)'
  name: MinsPerContact
  label: MinsPerContact
  description: |
    MinsPerContact should not be empty if StartingRateInPop contains value.
  meta:
    severity: error
- expr: 'if(is.na(StartingRateInPop)) !is.na(References.Notes)'
  name: Missing_StartingRateInPop
  label: Missing_StartingRateInPop
  description: |
    References/Notes should not be empty, if StartingRateInPop is empty.
  meta:
    severity: warning
- expr: '!is.na(RelevantPop)'
  name: RelevantPop_missing
  label: RelevantPop_missing
  description: |
    ReleventPop should not be empty. If it does not apply to a specific population (for example if it is an overhead task with fixed weekly hours),
    then select the "-" from the dropdown to indicate that the population selection is not applicable.
  meta:
    severity: error
- expr: 'if(!is.na(StartingRateInPop)) RelevantPop!="-"'
  name: RelevantPop_undefined
  label: RelevantPop_undefined
  description: |
    RelevantPop cannot be '-' if StartingRateInPop is present
  meta:
    severity: error
- expr: 'if (!is.na(AnnualDeltaRatio)) in_range(AnnualDeltaRatio, min=0.98, max=1.02)'
  name: AnnualDeltaRatio_value_Range
  label: AnnualDeltaRatio_value_Range
  description: |
    AnnualDeltaRatio typically within 1.0 +/- 2%. Large value compounded over long time horizon produces questionable predictions.
  meta:
    severity: info
- expr: 'if(!is.na(StartingRateInPop)) StartingRateInPop >= 0 & if(!is.na(RateMultiplier)) RateMultiplier >= 0 & if(!is.na(AnnualDeltaRatio)) AnnualDeltaRatio >= 0 & if(!is.na(NumContactsPerUnit)) NumContactsPerUnit >= 0  & if(!is.na(NumContactsAnnual)) NumContactsAnnual >= 0 & if(!is.na(MinsPerContact)) MinsPerContact >= 0 & if(!is.na(HoursPerWeek)) HoursPerWeek >= 0'
  name: Nagative_TaskColumns
  label: Nagative_TaskColumns
  description: |
    These values in TaskValue_ref sheet cannot be negative.
  meta:
  severity: error

