---
options:
  lin.eq.eps: 1e-08
  lin.ineq.eps: 1e-08
---

rules:
- expr: 'Male >= 0 & Female >= 0'
  name: Population_Size
  label: Population_Size
  description: |
    Population sizes must be greater than or equal to zero.
  meta:
    severity: error
- expr: '(if (!is.na(as.integer(Age)) & as.integer(Age) >0) in_range(abs(Male/Female), min=0.85, max=1.15)) & (if(Age=="<1") in_range(abs(Male/Female), min=0.99, max=1.01))'
  name: Gender_Imbalance
  label: Gender_Imbalance
  description: |
    The male and female population sizes are typically approximately 50/50 at birth and within 10-15% of each other in total.
    Valid reasons for imbalance between the sexes would be extended war-caused male mortality or high levels of maternal mortality.
    Please validate that the population split is supposed to be this different.
  meta:
    severity: warning

