---
options:
  lin.eq.eps: 1e-08
  lin.ineq.eps: 1e-08
---

rules:
- expr: 'if (!is.na(Year0)) in_range(Year0, min=0.0, max=1.0)'
  name: CoverageRate_range
  label: CoverageRate_range
  description: |
    If specified, coverage rate must be between 0.0 and 1.0
  meta:
    severity: error

