name: update build agent

on:
  workflow_dispatch:
   inputs:
     tags:
       description: 'image tags' 
       required: false
       default: mewu/rimage:pandoc

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.build
          push: true
          tags: ${{ github.event.inputs.tags }}