name: EHEP Dev Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '4.2' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'R.version'
      
      - name: Setup Dependency
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            rcmdcheck
          working-directory: 'ehep'
          
      - name: Check Package     
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"' 
          working-directory: 'ehep'
         
      - name: Upload Check Log    
        uses: actions/upload-artifact@v3
        with:
          name: check_log
          path: check
