name: PACE-HRH Devtools build and test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
    paths:
      - 'pacehrh/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mewu/rimage:pandoc
    steps:
      - uses: actions/checkout@v2
      - name: Check package
        run: |
          apt-get install texinfo
          R CMD check pacehrh --as-cran
        
      - name: Setup Dependency
        working-directory: 'tests/setup'
        run: |
          Rscript install_dep_for_tests.R
      
      - name: Run unittest
        working-directory: 'pacehrh'
        run: Rscript -e 'devtools::test()'
