name: EHEP Devtools build and test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
	container:
      image: mewu/rimage
    steps:
      - uses: actions/checkout@v2
      - name: Check package
        working-directory: 'ehep'
        run: Rscript -e 'devtools::check()'
      - name: Run unittest
        working-directory: 'ehep'
        run: Rscript -e 'devtools::test()'
