name: PACE-HRH Integration Tests
# This job is used for all non-unit tests
on:
  # todo:  we need to decide later if these tests are only run on releases
  pull_request:
    branches:
      - "main"
jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Install devtools
        run: |
          Rscript -e "options(install.packages.compile.from.source = "never"); install.packages('devtools')"
      - name: Install pandoc
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install pandoc  
      - name: Setup Dependency
        working-directory: 'tests/setup'
        run: |
          Rscript install_dep_for_tests.R    
      - name: Install packages
      # todo: using Readme instruction to install package
        run: |
          Rscript -e "install.packages('httpuv', build = FALSE, type = 'win.binary')"
          Rscript -e "devtools::install_local('pacehrh', force=TRUE, upgrade='always', repos = NULL, build=TRUE, dependencies=TRUE)"
        shell: cmd
      - name: Run Integration tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat/', reporter = c('fail', 'progress','summary'))"
        env:
          NOT_CRAN: true
          
      - name: Check input spreadsheet
        run: |
          Rscript -e "rmarkdown::render('validation_report.Rmd', 'html_document', params=list(inputFile='config/model_inputs.xlsx', outputDir='log'), output_dir='log')"
      - uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: log
