name: EHEP Integration Tests
# This job is used for all non-unit tests
on:
  # todo:  we need to decide later if these tests are only run on releases
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - 'ehep/**'
jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Install devtools
        run: |
          Rscript -e "install.packages('devtools')"
      - name: Install packages
        run: |
          # todo: using Readme instruction to install package
          Rscript -e 'devtools::install_local("ehep", force=TRUE, upgrade="always", repos = NULL, build=TRUE)'
      - name: Run Integration tests
        run: |
          Rscript -e "testthat::test_dir('tests/testthat/', reporter = 'stop')"
          